#[derive(Debug, PartialEq)]
pub enum Error {
    Encoding,
    InvalidIdentityArgs,
    InvalidIdentityRule,
    InvalidCardinality,
    InvalidSchemaVersion,
    InvalidReceiverId,
    InvalidLatitude,
    InvalidLongitude,
    InvalidAltitude,
    InvalidStatus,
    MissingCapabilities,
    InvalidCapability,
    DuplicateCapabilities,
    MissingModeS,
    InvalidUpdatedAt,
    InvalidStreamProtocol,
    InvalidStreamFormat,
    StreamProtocolRequired,
    InvalidMetadataHash,
    RevokedStream,
    InvalidSequence,
    InvalidTransition,
    ImmutableReceiverId,
    RevokedTerminal,
}

impl Error {
    pub fn as_i8(&self) -> i8 {
        match self {
            Error::Encoding => -2,
            Error::InvalidIdentityArgs => -3,
            Error::InvalidIdentityRule => -4,
            Error::InvalidCardinality => -5,
            Error::InvalidSchemaVersion => -9,
            Error::InvalidReceiverId => -10,
            Error::InvalidLatitude => -11,
            Error::InvalidLongitude => -12,
            Error::InvalidAltitude => -13,
            Error::InvalidStatus => -14,
            Error::MissingCapabilities => -15,
            Error::InvalidCapability => -16,
            Error::DuplicateCapabilities => -17,
            Error::MissingModeS => -18,
            Error::InvalidUpdatedAt => -19,
            Error::InvalidStreamProtocol => -20,
            Error::InvalidStreamFormat => -21,
            Error::StreamProtocolRequired => -22,
            Error::InvalidMetadataHash => -23,
            Error::RevokedStream => -24,
            Error::InvalidSequence => -25,
            Error::InvalidTransition => -26,
            Error::ImmutableReceiverId => -27,
            Error::RevokedTerminal => -28,
        }
    }
}
