[[cells]]
name = "receiver_registry"
enable_type_id = true
location = { file = "/Users/jeremicarose/Downloads/mlat-system 2/evidence/registry-v2-review-2026-09-11-final/contract/receiver-registry" }

[[cells]]
name = "lifecycle_funding"
enable_type_id = false
location = { file = "/Users/jeremicarose/Downloads/mlat-system 2/deploy/registry-v2-testnet-2026-09-11-data1/lifecycle-funding.bin" }

[lock]
code_hash = "0x9bd7e06f3ecf4be0f2fcd2188b23f1b9fcc88e5d4b65a8637b17723bbda3cce8"
args = "0x1eed21522d7c686da5695111d790c4aab8a2c181"
hash_type = "type"
